### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by b0jan** [slowe/VirtualSky#17]
Really like the project, but i don't like that it's not dependency free. 
Woudn't be better in vanilla js?

**Comment by slowe** [comment]
There hasn't been an explanation for what the dependency is so I'm closing this.

**Comment by slowe** [comment]
There is no longer a dependency on jQuery. I wrote my own smaller replacement. From version 0.7.0 it doesn't use jQuery. Instead it uses stuQuery.

**Comment by astromediaonly** [comment]
Sorry to bother but can I somehow get it to work if Im already using JQuery and dont want to include unnecessary stuff it can already do or am I required to include stuQuery anyways? It was probably not thought about during design process but it does not hurt to ask if there is some simple way :)
