### ISSUE TITLE
get ra and dec of clicked body

### ISSUE THREAD

**Issue by astroanu** [slowe/VirtualSky#25]
How can i get the ra/dec or other info of the clicked body?

**Comment by astroanu** [comment]
anybody?

**Comment by slowe** [comment]
Sorry. I've been cycling from Liverpool to Istanbul for the past two months. I'm not really sure what you mean by "clicked body"? Could you provide a little more context? Thanks.

**Comment by astroanu** [comment]
Oh..  long long journey 

By 'body' i meant celestial body (a star or a planet). I want to get the ra and dec values and may be other info regarding the body when the user clicks on it.

**Comment by slowe** [comment]
Not without quite a bit of work is the simple answer. The 'stars' and 'planets' you see on the screen are drawn pixels. There isn't currently a lookup mechanism to go backwards from pixel position to object.

**Comment by astroanu** [comment]
oh i see. it's because of the canvas ? If you are planning on something like that it would be really nice/. this is a really good plugin.  :metal:

**Comment by pludov** [comment]
I am in need for this feature ! Are you actively working on it ?

For now, I worded out finding the ra,dec coordinates from mouse/touch coordinates for all projections. I'll open a PR once it's cleaned up

**Comment by slowe** [comment]
There is now a `click` callback which can be used e.g. 
```
'callback': {
	'click': function(e){
		// The event includes e.x, e.y, e.ra, e.dec.
		// Get the nearest object based on the x/y cursor position
		e.nearest = e.data.sky.nearestObject(e.x,e.y);
		console.log(e.nearest);
	}
}
```

**Comment by pludov** [comment]
Long press is probably broken :
https://github.com/slowe/VirtualSky/commit/a43ab2383cca145083c8fc1703fd36ad4e69f7ba#r34608949
