### ISSUE TITLE
infinite loop when lang files not found

### ISSUE THREAD

**Issue by chrisnorth** [slowe/VirtualSky#28]
If the language file (e.g. `lang/en.json`) isn't found the page enters an infinite loop, each returning a 404 error). It looks like it's looking for the `lang` subdirectory from the website root directory, not the directory in which `virtualsky.js` is located

**Comment by Javarome** [comment]
I had a similar problem that I've fixed this fork: https://github.com/Javarome/VirtualSky
I still need to make a PR...

**Comment by slowe** [comment]
Should now be fixed.
