### ISSUE TITLE
VR Mode

### ISSUE THREAD

**Issue by Coder206** [slowe/VirtualSky#35]
@slowe Great work on VirtualSky - a great reason to love the Web! :) I think it would be great to have the ability to look around and view the sky using WebVR through a framework like [A-Frame](https://aframe.io/)

**Comment by slowe** [comment]
@Coder206 I appreciate it would be cool. To use that framework it looks as though Virtual Sky would need lots of re-writing. Unfortunately I don't have the time available to do all the work that would be necessary. I can't justify the expense. However, the code is open so you could fork this and make a version that does what you want.
