### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by giuseppeputzolu** [slowe/VirtualSky#36]
Hi All,
attached json file ([it_json.txt](https://github.com/slowe/VirtualSky/files/1023634/it_json.txt)) is the italian translation.
Regards,
Giuseppe

**Comment by slowe** [comment]
@giuseppeputzolu Molto grazie per la traduzione. Ecco la qua http://slowe.github.io/VirtualSky/embed.html?projection=stereo&lang=it
