### ISSUE TITLE
Map movement with gyroscope

### ISSUE THREAD

**Issue by espinozaortiz** [slowe/VirtualSky#38]
Hello
First I congratulate you on your work. I ask you a question; I want to control the stellar map with the gyroscope or with the compass. What part of the code should I intervene? I try but not succeed.
thanks for your help

**Comment by slowe** [comment]
@espinozaortiz How exactly you are trying to control it with a gyroscope or compass? Presumably you are wanting a gnomic projection like in example 8? http://slowe.github.io/VirtualSky/#ex8

If you have some code that is separately calculating the RA/Dec of where you want to be centred you can set the RA/Dec and redraw the canvas e.g. 
```js
// Initial setup
var planetarium = S.virtualsky({config options here});

// Set the coordinates (decimal degrees) and update the screen
planetarium.setRADec(83.8220792,-5.3911111).draw()
```

**Comment by slowe** [comment]
I guess this might have answered the question.

**Comment by espinozaortiz** [comment]
Sorry for not answering. I solve my problem using another system. Virtual
Sky does not work for me. Thank you for your time and for answering my
questions. regards
