### ISSUE TITLE
labels etc not showing up

### ISSUE THREAD

**Issue by dmcclure2018** [slowe/VirtualSky#45]
Hi. Firstly, thanks for the project. I absolutely love it.  I've been trying to install it on my server and have all of the code and a page up and running which is working except for the fact that none of the constellations, planets, stars or their labels are showing up. All the files are included and in the correct place but they just don't seem to be working. Please help.

**Comment by dmcclure2018** [comment]
hadn't added json mime type to IIS. Apologies

**Comment by slowe** [comment]
@dmcclure2018 No worries. :)

**Comment by slowe** [comment]
@dmcclure2018 Also, I've just released version 0.7.0.
