### ISSUE TITLE
Constellation Line Thickness

### ISSUE THREAD

**Issue by lightningawesome** [slowe/VirtualSky#46]
Hello,

Is it possible to implement a change in line thickness for the constellation and radial lines?  They are quite thin and difficult to see on my page since my space is fairly small (only 300x300).  I am using the Polar projection. 

Thank you,

**Comment by slowe** [comment]
@lightningawesome Sorry for taking a while to respond. I've been busy with life. The current test version (0.7.0) now has some query string options for setting the width of the az/eq/gal grid lines (e.g. gridlineswidth=5), constellation lines (e.g. constellationwidth=5), constellation boundaries (e.g. constellationboundarieswidth=5), and the galaxy (e.g. galaxywidth=5). Here's an example of the test version with equatorial gridlines of 5px width http://slowe.github.io/VirtualSky/0.7.0/embed.html?gridlineswidth=5&gridlines_eq=true Let me know if this is the sort of thing you were after.

**Comment by slowe** [comment]
I've made version 0.7.0 the live version so this issue should now be resolved on  http://slowe.github.io/VirtualSky/embed
