### ISSUE TITLE
Combine with Particle.js

### ISSUE THREAD

**Issue by UnaOmnia** [slowe/VirtualSky#49]
Can we make the stars fade or blink a little with Particle? Anyway to draw the canvas at once? Could make it a little more realistic that way... Was also thinking about shooting stars and the milky way... any ways to make it more realistic looking.

**Comment by slowe** [comment]
Particle.js seems to be for creating particles. It seems like overkill for a twinkle effect.

I don't understand what you mean by "anyway to draw the canvas at once?". You can draw on the canvas. I'm not sure what the "at once" means in this context. Do you mean on page load? Something else?

The Milky Way is available as a boundary in the style of Norton's Star Atlas.

The aim of this project isn't to be photo-realistic. If you need photo-realism, Stellarium might be better suited.

**Comment by UnaOmnia** [comment]
The milky way is not realistic, so it would be better for it to be an image instead of an outline, or a CSS/SVG imitation. I see the JS for drawing the stars etc, so I just need to add an animation to make them twinkle. 

https://codepen.io/bob6664569/pen/rOzmve

This is particle.js doing the same thing...

https://codepen.io/WebSonick/pen/vjmgu

Here is a custom made one doing the same thing - it is pretty simple. The only issue with either is the size and placement of the stars is not REAL, which is like VirtualSky. I am already doing what that project is doing, but with particle.js as the covering element:

dev.unaomnia.com

I feel the project aligns with realism more. Otherwise, I could just use these other projects and the location of the stars wouldn't be real but their appearance would be more realistic. 

THAT is why I think just adding a small bit of code in the JS drawing the stars. Or just adding a class, and then adding the animation with CSS. Just need a hint and I can do it myself. I am not the greatest with SVG drawing coding so I am having to reverse engineer your JS which will take me longer without your help.

That means I have to include particle.js separate which would increase load time I am guessing. I want to do it this way to improve performance. 

PS not nearly as hard as it will be for me to animate a rotating Saturn loop.

**Comment by UnaOmnia** [comment]
Also I don't think Stellarium works:

https://sourceforge.net/p/stellarium/discussion/278769/thread/bd7aa262/

Don't think embedding in a website is possible... I have searched... this is the best project I found...

**Comment by UnaOmnia** [comment]
Would also be cool if all of the planets and sun were more realistic and could be in frame rotating and the stars could correspond to their position, etc... yes hyper realism and the appearance of orbiting each planet... that is essentially what I am trying to do with my site's design.

**Comment by slowe** [comment]
Stellarium doesn't embed in a webpage, no. It wasn't clear to me what you were definitely trying to do something on the web or that you just wanted some kind of "hyper realism".

You want quite a few things that don't appear to fit with this project. By "rotating planets and sun" that might imply rotating on their own axes. Planet discs aren't visible in most of the full-sky views (which this project is primarily aimed at) so that would require arbitrary (unreal) scaling of the planets to make rotation visible. But you also say "appearance of orbiting each planet" which brings with it the obvious suggestion that you are actually after a 3D immersive universe much more akin to Celestia. This project is definitely not trying to be that for many, many, reasons.

This project uses HTML5 canvas. As such, individual stars are not HTML elements or SVG elements that can be styled with CSS. In fact, my code in this project doesn't draw SVG. I'm not sure how SVG is connected to you "reverse engineering" my code.

It would make much more sense for you to create your own project that does the things that you actually need. As far as I can tell, the only thing this project does that you need is to show stars in their correct relative positions.

**Comment by UnaOmnia** [comment]
All I really wanted to add to VirtualSky is:

- Make the stars flicker a bit like actual stars do. 
- Make the milky way more realistic than an outline.
- MAYBE a shooting star now and again.

AND the flickering stars is the most important, mostly because then particle.js can not be included and save a lot of loading time. Although perhaps I could figure out a faster loading way to cover and uncover the stars a bit than particle.js. 

I do not know much about CSS3 versus SVG versus canvas... Okay so to get it straight your project uses javascript to draw canvas... I was looking through that javascript... I saw the drawing of the stars... I was looking for a way to add an animation, right after they are drawn, to give them a blurred edge that grows and shrinks like a flicker, or just that they fade in opacity  and unfade, and/or have blurred edge... etc... I love the project, it would be cool and probably not to crazy intensive on load to add a little more realism... ANY pointers on where to look in the JS or where to maybe add an animation function and selectors to use in that function would be awesome.

**Comment by slowe** [comment]
@UnaOmnia I would imagine you might be best trying to look at where things are drawn because animation is a series of still images put together to create the illusion of movement. Perhaps you could put your animation function there somehow. I'm not sure on your implementation of the animation function or how/why selectors will be involved but good luck.

**Comment by UnaOmnia** [comment]
First, a weird thing happened last night (SUPER weird)... I was using WinSCP to edit my development site to relaunch my site... I walked away for a smoke and coffee and when I came back stars.json was pending upload to be saved, and I cancelled... I thought that is weird because I had no folders or anything open near that file what so ever... I had moved on from that portion of the project for a full day or two so it was odd...

So I decided to take a peak again (cuz I often check things like that out) and saw the updateColour function, which has the colors for the stars... I thought, maybe I could do a set timeout to change the color from hex to rgba with opacity and run that on a loop... I was unable to get it to work in one try... 

http://fabricjs.com/

Then I found this and thought about converting the canvas to SVG to use CSS to animate the stars. I do understand that I can make covering elements, but that is a bit limited in terms of style. Would be better to change opacity of the color of the star and/or add text shadow or box shadow that increases or decreases in size throughout the animation. Ultimately, looking for a bit of a flicker on them, because that is what you see in the sky - in the name Virtual Sky.

**Comment by UnaOmnia** [comment]
I had a better idea... 
I was thinking with the canvas it isn't animated and therefore the load time isn't high. I am not 100% but I was imagining a vector being drawn etc, and that each individual point wouldn't have to be kept track of, but instead a layer as one...

And that with SVG or many individual points, and animation, INSTEAD OF a covering element that fades, the load time would be considerably higher. 

But what if I created 3 identical canvas, except the magnitude or size of the star was changed, and then fade between them, so that they seem to grow and shrink from the same origin position, like a flicker...

**Comment by slowe** [comment]
@UnaOmnia Please fork the project and do things in your forked version.

**Comment by alex-w** [comment]
Hint: https://stellarium-web.org

**Comment by UnaOmnia** [comment]
Did you just tell me to go fork myself? Just kidding. I will do that... and Alex, I saw that, but I fail to see how it helps for web embed into your own site. Best you could do is iframe, maybe a few settings. Do you think that route is really plausible? Also, zoom in on Saturn. Doesn't spin. Meaning, likely wouldn't be animated, which is what I am going for all together. A life-like sky, which does in fact have some motion to it - when you look in the sky, the stars flicker. That has shooting stars, and different styled stars, which is pretty cool and accurate looking, but the stars do not appear to flicker at all. And the rendering isn't all that smooth...

**Comment by alex-w** [comment]
@UnaOmnia see https://github.com/Stellarium/stellarium-web-engine and https://github.com/Stellarium/stellarium-web
