### ISSUE TITLE
Language file being recursively called

### ISSUE THREAD

**Issue by AndreaGon** [slowe/VirtualSky#51]
Whenever I run Virtualsky version 0.7.0 on Chrome, the language json file is being recursively called. Refer to the picture:

![chromebug](https://user-images.githubusercontent.com/44361130/52911686-1b16fd80-32e2-11e9-91ea-ca07be63b6ab.JPG)

**Comment by alexandervlpl** [comment]
Anybody have a solution to this? The library is not usable like this: maximum CPU usage and the sky doesn't even appear for me.

**Comment by alexandervlpl** [comment]
Okay, this only happens when running VirtualSky locally (loading the JSON files from your filesystem). This breaks even if Chrome is started with `--allow-file-access-from-files`. A warning about this should be included somewhere.

**Comment by AndreaGon** [comment]
@alexandervlpl I recently made a PR on this issue, although I lack various testing environments.

**Comment by slowe** [comment]
@AndreaGon Thanks for the PR. The language code was trying to fall back to `en.json` if loading failed. Unfortunately, if it failed to load `en.json` (because of Chrome security settings) it tried to load it again. I've put in a check to stop this.
