### ISSUE TITLE
On mobile, touch events only slide the view in one direction

### ISSUE THREAD

**Issue by pludov** [slowe/VirtualSky#52]
Hello,

Congratulation for the great work !

I would like to embed VirtualSky in a telescope control panel dedicated to mobile phones (you can see it at https://github.com/pludov/mobindi ), but controls of the examples do not seem to work when used on an Android mobile phone.

For instance, for the Example 7 of the example page, the field only move around a top-left => bottom-right axis, and zoom by touch does not work. (I tested using chrome and firefox on Android)

Any idea ?

**Comment by pludov** [comment]
Fix available in Pull request #54

**Comment by pludov** [comment]
This is low effort to fix : the change in  the PR is trivial !

**Comment by slowe** [comment]
@pludov Thanks for the PR.
