### ISSUE TITLE
Is it possible to change the center of the sky (projection: gnomic)?

### ISSUE THREAD

**Issue by ghost** [slowe/VirtualSky#53]
now i am use the projection type of the "gnomic", 
and actually the virtual-sky is useful and help me a lot, 
but one thing really bother me is that when i use the panTo function, it is alway the opposite direction in my imagination.
To elaborate, it is mean i want to make the sky move right, but i will always move left.
So i want to change the center of the sky, is it possible?
Thanks for your attention.
It is alway appreciate that the useful tool.
Thanks you very much.

**Comment by slowe** [comment]
@bernie40916 Thanks for the comment. I'm not sure what you mean. The `panTo` will take the shortest route to the new coordinates. So the direction it moves will depend on that.
