### ISSUE TITLE
Canvas shape changes in different size

### ISSUE THREAD

**Issue by techyroots** [slowe/VirtualSky#63]
Hi, 

I have found that changing the size of the window disturbs the shape of the canvas and slightly the bg color too, why it's happening, 

below is the screenshot of before and after changing the size of the window

before : 
![Screenshot 2019-09-13 at 10 30 51 PM](https://user-images.githubusercontent.com/52959098/64880668-5d38cf80-d676-11e9-939c-5a5b9cbb61b1.png)

after: 
![Screenshot 2019-09-13 at 10 30 39 PM](https://user-images.githubusercontent.com/52959098/64880603-32e71200-d676-11e9-84bb-4e74e04652b7.png)
 
I really don't know. Can anyone help me here with some thoughts? Will really appreciate :)

**Comment by slowe** [comment]
@techyroots Your second screenshot appears to have the "atmosphere" turned on. The first doesn't. I don't know why it is changing as you change the window size. I can't replicate this. Do you have an online example where this happens?

On window resize, the canvas may be adapting to the size of the container you've given it.
