### ISSUE TITLE
Planets not displaying properly.

### ISSUE THREAD

**Issue by maphilli14** [slowe/VirtualSky#68]
I've been around this code many times and had my son help a bunch too.  I've been able to customize everything but the planets.  Is there anyway someone can help take a look?  https://maphilli14.github.io/allskyplanetarium/

TIA,

Mike

**Comment by slowe** [comment]
@maphilli14 It looks as though you are using an older version of [`virtualsky.js`](https://maphilli14.github.io/allskyplanetarium/virtualsky.js) (that uses jQuery) with a version of the planets plugin [`virtualsky-planets.js`](https://maphilli14.github.io/allskyplanetarium/virtualsky-planets.js) that is for the newer version of Virtual Sky (using stuQuery). Version 0.7.0 removed jQuery but your version (claiming to be "0.7") clearly uses jQuery. The planets plugin you are using doesn't know how to work as it is missing stuQuery. If you want to use this old (modified?) version of VirtualSky, you'll probably want to use an [old version of virtualsky-planets.js](https://github.com/slowe/VirtualSky/blob/51b70e3299b79ee78e177b4f9c0fc1100da7a6eb/virtualsky-planets.js)

**Comment by maphilli14** [comment]
@slowe downgrading the virtualsky-planets.js to the suggested version worked great, thanks!  I'll also try the updated versions you also mentioned!  Thanks!
