### ISSUE TITLE
runing problem

### ISSUE THREAD

**Issue by hmovahedim** [slowe/VirtualSky#88]
Hello
I have this problem.
Can you help me ?
![image](https://user-images.githubusercontent.com/26388023/144835447-9a850cde-0d3b-4301-8988-4c2a6a9529dd.png)

**Comment by michealroberts** [comment]
Hi @hmovahedim I'm not a core maintainer of this project. However, I suspect you're trying to invoke something too early in the lifecycle of the page.

Could you give an example of your instantiation of "`S`"...

You may need something like this:

```
S(document).ready(function(){}
```

**Comment by hmovahedim** [comment]
> Hi @hmovahedim I'm not a core maintainer of this project. However, I suspect you're trying to invoke something too early in the lifecycle of the page.
> 
> Could you give an example of your instantiation of "`S`"...
> 
> You may need something like this:
> 
> ```
> S(document).ready(function(){}
> ```

I put this in S(document).ready(function(){}) but it isn't work.
May this depend to jquery version ?

**Comment by michealroberts** [comment]
Have you added this as well before the `virtualsky.js` script element?

```
<script src="stuquery.min.js"></script>
```

If yes, are both of these scripts locally available in your project root?

**Comment by slowe** [comment]
Hello @hmovahedim, did you try to follow the instructions at https://slowe.github.io/VirtualSky/? That's a good place to start.

Your error message seems to suggest that you haven't included stuquery (which is included in this repo). Note that jQuery is not used in this project so your version of jQuery (that you are presumably including for other reasons) shouldn't matter.

**Comment by hmovahedim** [comment]
Thank.
