### ISSUE TITLE
Add custom ground

### ISSUE THREAD

**Issue by esh-g** [slowe/VirtualSky#92]
Is it possible to add a custom image or colour as the ground in a gnomic projection? If yes, then how?

**Comment by slowe** [comment]
@Someone-here There isn't. All the projections have been implemented as simply as possible to keep the size down. That means that solid polygons are harder to implement so they haven't really been done.

**Comment by esh-g** [comment]
@slowe  Could you please recommend another library that has that functionality?

**Comment by esh-g** [comment]
I need it urgently for a client
