### ISSUE TITLE
German language problem

### ISSUE THREAD

**Issue by RoamingSquirrel** [slowe/VirtualSky#94]
This is a very good application. 

One small issue, German is listed as a supported language but it looks like the json file for German is missing so the application fails if German is chosen as a language option.

**Comment by RoamingSquirrel** [comment]
I think that the problem lies in the difference between the virtualsky.js and the virtualsky.min.js files.

In the virtualsky.js files, the languages referenced are: ar, cs, de, en, es, fr, gl, it, nl, pl, pt
In the virtualsky.min.js file, the languages references are: ar, cs, en, es, fr, it, nl, pt

**Comment by slowe** [comment]
@RoamingSquirrel Sorry for only just finding this comment now. AFAIK the German language does load e.g. https://slowe.github.io/VirtualSky/embed?lang=de It uses the German language file at https://github.com/slowe/VirtualSky/blob/gh-pages/lang/de.json Do you have more details about the specific scenario in which it doesn't work?

**Comment by RoamingSquirrel** [comment]
No worries thanks, I figured it out ... the problem lies in the difference between the virtualsky.js and the virtualsky.min.js files.
In the virtualsky.js file the code includes:
this.langs = {
		'ar': { "language": {"name": "&#1575;&#1604;&#1593;&#1585;&#1576;&#1610;&#1577;","alignment": "right" } },
		'cs': { "language": {"name": "&#268;e&#353;tina","alignment": "left" } },
		'de': { "language": {"name": "Deutsch","alignment": "left" } },
		'en': { "language": {"name": "English","alignment": "left" } },
		'es': { "language": {"name": "Espa&#241;ol","alignment": "left" } },
		'fr': { "language": {"name": "Fran&#231;ais","alignment": "left" } },
		'gl': { "language": {"name": "Galego","alignment": "left" } },
		'it': { "language": {"name": "Italiano","alignment": "left" } },
		'nl': { "language": {"name": "Nederlands","alignment": "left" } },
		'pl': { "language": {"name": "Polski","alignment": "left" } },
		'pt': { "language": {"name": "Portugu&#234;s","alignment": "left" } },
	}; 
Whereas in the virtualsky.min.js file the code only includes:
this.langs={
              ar:{language:{name:"&#1575;&#1604;&#1593;&#1585;&#1576;&#1610;&#1577;",alignment:"right"}},
              cs:{language:{name:"&#268;e&#353;tina",alignment:"left"}},
              en:{language:{name:"English",alignment:"left"}},
              es:{language:{name:"Espa&#241;ol",alignment:"left"}},
              fr:{language:{name:"Fran&#231;ais",alignment:"left"}},
              it:{language:{name:"Italiano",alignment:"left"}},
              nl:{language:{name:"Nederlands",alignment:"left"}},
              pt:{language:{name:"Portugu&#234;s",alignment:"left"}},
};
It works fine using the virtualsky.js file.
