### ISSUE TITLE
clarification on terms of use

### ISSUE THREAD

**Issue by wykhuh** [slowe/VirtualSky#96]
On the Virtualsky site, it says "It is provided freely for educational and non-profit use."

In a [issue 43](https://github.com/slowe/VirtualSky/issues/43), you said "Basically, if you credit [Las Cumbres Observatory](https://lco.global/)/Stuart Lowe (somewhere appropriate) and add a link to this github repo I'm pretty happy."

I own a [Dwarf II smart telescope](https://dwarflab.com/products/dwarf-2-smart-telescope), and I would like to build an open source web app that controls the Dwarf II. I would like to add VirtualSky to the app. I don't work for the company that makes Dwarf II, I just own the scope. Can I use VirtualSky in the app? Here's the [repo for the app](https://github.com/DwarfTelescopeUsers/dwarfii-stellarium-goto)

**Comment by slowe** [comment]
@wykhuh As it says, add a credit+link back. I am still no more capable of deciding on the "correct" licence. I originally created this code (~2010/11) when there were no web-based alternatives and I rarely have time to maintain/update this any more. I definitely don't provide support. If you are likely to be wanting to make changes you should probably make a fork of this. 

Given that you currently seem to interface with Stellarium desktop, would [the Stellarium web engine](https://github.com/Stellarium/stellarium-web-engine) not be a natural choice to use?

**Comment by wykhuh** [comment]
@slowe Thanks for the reply.  Since I'm building an open source project for a commercial telescope, I figure it would be good to double check permissions.

I also contacted Stellarium web engine about using their code for my project. I sent an email to Stellarium web engine, and posted on the Stellarium google group, but I haven't heard back yet.  They use a stricter GPL-AGPL license.

If I end up using VirtualSky, I will add credit+link back, and work on a fork.

**Comment by wykhuh** [comment]
The people from Stellarium web said I can use their library for my project, so I will use Stellarium web for my project. 

Thanks!
