### ISSUE TITLE
Panning in `stereo` projection

### ISSUE THREAD

**Issue by eouia** [slowe/VirtualSky#97]
Thanks for the great library.

I don't know anything about astronomy at all, but in the end, I manage to somehow show the planetarium in my project.
`stereo` projection in my location is amazing and perfect for my needs.
Now what I want is, panning the planetarium around me, but I don't know how. What I want is to display the North direction, then West, South, East and then finally return to north again, like I'm turning around in my backyard.
 
I tried to use `panTo` method but failed. Doesn't it work with `stereo` projection? (with `gnome` projection, it works)
Is there any good way to animate(panning) the `stereo` projection? Mouse or keyboard can pan it, so probably there is a way to do it, but I cannot guess.

(I want to show this animation to my daughter on the `MagicMirror` in her room as a gift.)

Or should I redraw repeatedly with AZ offset?

**Comment by eouia** [comment]
I found `changeAzimuth()`. Thanks!

**Comment by slowe** [comment]
@eouia I'm glad you managed to find what you needed.
